shadimanna/dhl-logistic-services-for-woocommerce

pr-dhl-woocommerce/assets/css/pr-dhl-admin.css
pr-dhl-woocommerce/assets/js/pr-dhl.js
pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-express.php

Total packages change to dropdown and package number to textbox

Package revisions - dropdown and textbox

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-order-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-order.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-settings.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/class-dhlpwc-controller-cart.php

- Fixed an issue with delivery times not always loading in the right order
- Fixed an issue that causes Customizer not to load on specific themes

Update ParcelNL to 1.2.4

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.parcelshop.locator.js
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/class-dhlpwc-template.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-shipment.php

- Fixed automatic order id reference not being added for bulk
- Fixed ServicePoint locator not loading
- Added developer methods to update templates

DHL Parcel update v1.2.6

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.deliverytime.js
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/logic/class-dhlpwc-model-logic-shipment.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-delivery-times.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-parcelshop.php

- Fixed delivery times not loading for newest WooCommerce release
- Fixed an issue where postal code is case sensitive

Parcel NL update to 1.2.10 (internal division number)

---

pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-settings.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed an issue with warnings when loading settings

Release 2.2.1 hotfix DHL Parcel

---

pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-order-meta-option.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-shipment.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Improved mailpost bulk processing

Release 2.2.4 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.admin.load-switcher.js
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/isolated/class-dhlpwc-controller-isolated-load-switcher.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Added a fallback notice for switching between DHL Parcel and Deutsche Post International

Release 2.2.5 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.settings.js
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed an issue with certain settings not being able to save with certain themes

Release 2.2.9 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/isolated/class-dhlpwc-controller-isolated-load-switcher.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed an issue where the DPI module was not loading on certain pages

Release 2.2.10 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-condition-rule.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-parceltypes.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed an issue where decimals were not calculated correctly in conditional rules for delivery options

Release 2.5.9 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/class-dhlpwc-autoloader.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed autoloader for PHP8

Release 2.5.11 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.parcelshop.locator.js
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-label-metabox.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Small fix for ServicePoint locator in checkout

Release 2.7.5 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-order-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/logic/class-dhlpwc-model-logic-access-control.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/meta/class-dhlpwc-model-meta-order-label.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-access-control.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-label-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-order-meta.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-shipment.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-snippets.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/woocommerce/settings/class-dhlpwc-model-woocommerce-settings-shipping-method.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/cart/parcelshop-locator.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Added a new available action hook for label creation

Release 2.8.1 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-order-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-product.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/function-dhlpwc-esc-template.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-escape-output.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/admin/action-button-container.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/admin/order/delivery-times.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/admin/settings/condition/row.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/cart/delivery-times-option.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/cart/parcelshop-option.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/mail/plain/service-point.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/mail/service-point.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/mail/track-and-trace.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/modal.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta-container.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/form/options-container.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/form/options.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/form/size.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/form/sizes-container.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/label-container.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/order/meta/label.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/parcelshop-info.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/track-and-trace.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Added additional sanitization, escapes and validation
* DHL Parcel: Updated readme
* DHL Parcel: Standalone release

Release 2.8.6 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/assets/js/dhlpwc.migrate.js
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-migrate.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-settings.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/logic/class-dhlpwc-model-logic-access-control.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/logic/class-dhlpwc-model-logic-shipment.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-access-control.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/woocommerce/settings/class-dhlpwc-model-woocommerce-settings-shipping-method.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/admin/migrate.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/view/mail/debug.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Added a migration notification for current users
* DHL Parcel: Updated listing tags

Release 2.8.8 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Fixed a bug with pages not loading when DHL for WooCommerce and DHL Parcel for WooCommerce are both activated

Release 2.8.10 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/class-dhlpwc-controller-mail.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-label-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-order-meta.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-shipment.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-track-trace.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Updated tracking url for Belgium
* DHL Parcel: Updated product-based automatic mailbox selection to work with areas where mailbox delivery is not available when used with bulk actions
* DHL Parcel: Fixed an issue where product-based automatic mailbox selection is being applied to sequential orders when used in a bulk action

Release 2.8.11 (DHL Parcel)

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-migrate.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Updated the migration notice when to change colors

Release 2.8.14 (DHL Parcel)

---

pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Paket: Fix for countries with no zip format. Error creating a label.
* DHL Paket: Fix the displayed warning in the empty row in order table.
* DHL Paket: Update Readme description.

Paket api 30 - Release version 2.8.15

---

pr-dhl-woocommerce/dhlpwoocommerce/README.md
pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/controller/admin/class-dhlpwc-controller-admin-order.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/logic/class-dhlpwc-model-logic-label.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-label-metabox.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-label.php
pr-dhl-woocommerce/dhlpwoocommerce/includes/model/service/class-dhlpwc-model-service-shipment.php
pr-dhl-woocommerce/dhlpwoocommerce/readme.txt
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.txt

* DHL Parcel: Updated label downloads to now serve from the temporary folder instead of the public folder for additional security and storage usage

Release 3.0.1 (DHL Parcel)

---

pr-dhl-woocommerce/lib/PDFMerger/PDFMerger.php
pr-dhl-woocommerce/lib/PDFMerger/tcpdf/fpdf_tpl.php
pr-dhl-woocommerce/lib/PDFMerger/tcpdf/tcpdf_parser.php
pr-dhl-woocommerce/lib/PDFMerger/tcpdf/tcpdi.php

Tcpdf namespace

---

pr-dhl-woocommerce/includes/class-pr-dhl-wc-wizard-paket.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php

Not tested all urls, just the ones i direclty saw and used that needed a change.

Change old URLS

---

pr-dhl-woocommerce/includes/Utils/API_Utils.php
pr-dhl-woocommerce/includes/abstract-pr-dhl-wc-order.php
pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-deutsche-post.php
pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-ecomm.php
pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-ecs-asia.php
pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.md
pr-dhl-woocommerce/readme.txt

https://wordpress.org/support/topic/fatal-error-since-update-3-4-6/

Fix WC old versions compatibility

---

pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-rest-parcel-de.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.md
pr-dhl-woocommerce/readme.txt

Fix Parcel DE REST API links

---

pr-dhl-woocommerce/assets/css/pr-dhl-admin.css
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.md
pr-dhl-woocommerce/readme.txt

Fixing the empty settings on WC 8.4.0 by changing the css as WC 8.4.0 adding more element into the WC Settings HTML.

Fix empty settings on WooCommerce 8.4.0

---

pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-deutsche-post.php

Fix WooCommerce emails customizer plugins compatibility for DP

Fix WooCommerce emails customizer plugins compatibility for DP

---

pr-dhl-woocommerce/pr-dhl-woocommerce.php

fix Deutsche Post Test Connection

---

pr-dhl-woocommerce/includes/class-pr-dhl-wc-notice-soap-deprecation.php
pr-dhl-woocommerce/pr-dhl-woocommerce.php
pr-dhl-woocommerce/readme.md
pr-dhl-woocommerce/readme.txt

Closes # .
1.
2.
3.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Show soap api depecration notice
